import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import dynamic from "next/dynamic";
import Header from "@/components/Header";
import { UserProvider } from "@/context/UserContext";
import { OrdersProvider } from "@/context/OrdersContext";
import { ProductsProvider } from "@/context/ProductsContext";
const AuthProvider = dynamic(() =>
  import("@/context/AuthContext").then(mod => ({
    default: mod.AuthProvider,
    ssr: false
  }))
);
const CartProvider = dynamic(() =>
  import("@/context/CartContext").then(mod => ({
    default: mod.CartProvider,
    ssr: false
  }))
);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <UserProvider>
            <CartProvider>
              <OrdersProvider>
                <ProductsProvider>
                  <Toaster position="top-center" reverseOrder={false}/>
                  <div className="bg-white text-black min-h-screen">
                    <Header/>
                    {children}
                  </div>
                </ProductsProvider>
              </OrdersProvider>
            </CartProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
